spring:
 datasource:
  url: jdbc:mysql://localhost:3306/poke_data
  username: satoshi
  password: getpokemon
  driver-class-name: com.mysql.cj.jdbc.Driver
 sql:
  init:
   mode: always

mybatis:
 configuration:
  map-underscore-to-camel-case: true
 type-aliases-package: com.hot.backend.model

 